### ISSUE TITLE
Use GHA to automate deployment

### ISSUE THREAD

**Issue by enebo** [Metropolitan-Council/covid-poops#64]
Here is an example of using cron to run a job once a day:

https://github.com/jruby/jruby/blob/master/.github/workflows/nightly-snapshot-publish.yml

The deploy action already appears to use R so I am wondering if the whole data processing step can be automated?  I don't use R and I did not look at how this is all generated so I am not sure if this is a reasonable idea or not.

**Comment by eroten** [comment]
Hi @enebo. Thanks for opening an issue!

You are correct, the Shiny app deploy happens using GHA. This works well for us because we can push up the data updates and have the app update all in one go. However, we receive updated data from the University of Minnesota Genomics lab once a week. Samples are taken daily, but are tested and analyzed once a week. 

See #61 for more detail.
